# PostgreSQL. Versions 9.3 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DB_HOST']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>

development:
  <<: *default
  database: app_js_test_development

test:
  <<: *default
  database: app_js_test_test

production:
  <<: *default
  database: app_js_test_production
  # username: spending
  # password: <%= ENV["SPENDING_DATABASE_PASSWORD"] %>
